# -*- coding: utf-8 -*-
"""4.SVC_Breastcancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRuLmsMmDfdIImpUcAbvtOfZC8wEK2G3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay

d = load_breast_cancer()

d

d.keys()

df = pd.DataFrame(d.data,
                  columns = d.feature_names)


df["target"] = d.target


df

df.shape

df.info()

df.isna().sum()

df["target"].value_counts().plot(kind="bar", color=["peru", "darkmagenta"]);

corr_matrix = df.corr()
fig, ax = plt.subplots(figsize=(15, 10))
ax = sns.heatmap(corr_matrix)

X = d.data
y = d.target


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("SVM Accuracy on Breast Cancer dataset:", accuracy)

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=d.target_names)
disp.plot()
plt.title("Confusion Matrix for Breast Cancer")
plt.show()